language: python

os:
  - linux

python:
#  - "2.7"
#  - "3.4"  # Jessie
#  - "3.5"  # Stretch
  - "3.6"
  - "3.7"  # Buster
  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

cache: pip

install:
  - pip install -r requirements_test.txt

script:
  - coverage run --source=snakelib -m unittest

after_success:
  - coveralls 
