language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.8"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=snakelib -m unittest

after_success:
  - coveralls 
